apiVersion: v1
kind: Service
metadata:
  name: my-first-service
  annotations:
    # https://okteto.com/docs/cloud/private-endpoints/
    dev.okteto.com/auto-ingress: "private"
spec:
  selector:
    component: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
