name: "setup go with cache"
description: "uses in composite action"

inputs:
  go-version:
    description: "go version"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{inputs.go-version}}
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

