apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: dev
rules:
  - apiGroups: ["*"]
    resources:
      - pods
      - services
      - deployments
      - pods/portforward
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-rolebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-role
subjects:
  - kind: ServiceAccount
    name: sample-account
    namespace: users
