apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-account
  namespace: users

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-account-role-binding-base
  namespace: users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: sample-account
