# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  go-helloworld:
    type: boolean
    default: false

orbs:
  go: circleci/go@1.6.0

commands:
  go-setup:
    description: "goのセットアップ"
    steps:
      - go/load-cache
      - go/mod-download
      - go/save-cache

jobs:
  pass:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run: echo "This job is nothing to do. Because without the job, the workflow will fail."

  go-helloworld-build:
    working_directory: ~/repo/go/helloworld
    executor:
      name: go/default
      tag: '1.16.3'
    steps:
      - checkout:
          path: ~/repo
      - go-setup
      - run:
          name: Build
          command: |
            go build
      - run:
          name: Exec
          command: |
            ./helloworld

  go-helloworld-test:
    working_directory: ~/repo/go/helloworld
    executor:
      name: go/default
      tag: '1.16.3'
    steps:
      - checkout:
          path: ~/repo
      - go-setup
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

  go-helloworld-lint:
    working_directory: ~/repo/go/helloworld
    docker:
      - image: golangci/golangci-lint:v1.39.0
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Lint
          command: |
            golangci-lint run -v

  try-matches:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: "echo Hello mathces!"
      - when:
          condition:
            matches:
              pattern: "^main$"
              value: << pipeline.git.branch >>
          steps:
            - run: "echo Hello matches with step"
      - run: "Done!!"

workflows:
  version: 2

  pass:
    when:
      not: << pipeline.parameters.go-helloworld >>
    jobs:
      - pass

  go-helloworld:
    when: << pipeline.parameters.go-helloworld >>
    jobs:
      - go-helloworld-build
      - go-helloworld-test
      - go-helloworld-lint

  try-matches:
    when:
      matches:
        pattern: "^try-matches$"
        value: << pipeline.git.branch >>
    jobs:
      - try-matches
