apiVersion: v1
kind: Service
metadata:
  name: atlantis
  annotations:
    # https://okteto.com/docs/cloud/ssl/
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: atlantis
      port: 80
      targetPort: 4141
  selector:
    app: atlantis
