apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: playground
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/korosuke613/playground
  ref:
    branch: try-tf-controller


