on:
  pull_request:

jobs:
  hello_world_default:
    runs-on: codebuild-korosuke613_playground_github_actions_test-${{ github.run_id }}-${{ github.run_attempt }}
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
    container: ubuntu
    steps:
      - run: echo "Hello World!"
      - run: cat /etc/os-release 
      - run: curl http://localhost:8080
