on:
  workflow_dispatch

jobs:
  normal-job:
    runs-on: ubuntu-20.04
    steps:
      - run: sleep 5

  concurrency-job:
    runs-on: ubuntu-20.04
    concurrency:
      this_is_concurrency_job
    steps:
      - run: sleep 60

  dependent-job:
    runs-on: ubuntu-20.04
    needs:
      - normal-job
    concurrency:
      this_is_concurrency_job_2
    steps:
      - run: sleep 20

  after-job:
    runs-on: ubuntu-20.04
    needs:
      - dependent-job
    concurrency:
      this_is_concurrency_job
    steps:
      - run: sleep 5
