name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.5.0
        with:
          output_file: "repo-diagram.svg"
      - name: commit and push
        run: |
          git status --porcelain
          [[ -z $(git status --porcelain) ]] && exit 0; true

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          export NOW_DATE_TIME=$(date '+%Y-%m-%dT%H:%M:%S%z')

          git add repo-diagram.svg
          git commit -m "Updated most used languages ($NOW_DATE_TIME)"
          git pull
          git push origin "${GITHUB_REF##*/}"
