name: CI Renovate
on:
  pull_request: 
    paths:
      - 'renovate.json'
  push:
    branches: [main] # デフォルトブランチでキャッシュを保持するために main ブランチでも実行
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Renovate changed."
