name: CI
on:
  pull_request: 
  push:
    branches: [main] # デフォルトブランチでキャッシュを保持するために main ブランチでも実行
jobs:
  changed_types:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changed_files.outputs.frontend_any_changed }}
      backend: ${{ steps.changed_files.outputs.backend_any_changed }}
      renovate: ${{ steps.changed_files.outputs.renovate_any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0 # ファイルの変更を取得するために必要
      - env:
          TMP_FILE: ${{ runner.temp }}/changed_files.txt
        run: |
          git fetch origin main
          git diff --name-only ${{ github.base_ref || 'HEAD^' }} > $TMP_FILE
          grep --quiet '^frontend/' $TMP_FILE && echo "frontend=true" >> $GITHUB_OUTPUT
          grep --quiet '^backend/' $TMP_FILE && echo "backend=true" >> $GITHUB_OUTPUT
          grep --quiet '^renovate.json$' $TMP_FILE && echo "renovate=true" >> $GITHUB_OUTPUT

  frontend:
    runs-on: ubuntu-latest
    needs: changed_types
    if: needs.changed_types.outputs.frontend == 'true'
    steps:
      - run: echo "Frontend changed."
  backend:
    runs-on: ubuntu-latest
    needs: changed_types
    if: needs.changed_types.outputs.backend == 'true'
    steps:
      - run: echo "Backend changed."
  renovate:
    runs-on: ubuntu-latest
    needs: changed_types
    if: needs.changed_types.outputs.renovate == 'true'
    steps:
      - run: echo "Renovate config changed."
