name: CI
on:
  pull_request: 
  push:
    branches: [main] # デフォルトブランチでキャッシュを保持するために main ブランチでも実行
jobs:
  changed_types:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changed_files.outputs.frontend_any_changed }}
      backend: ${{ steps.changed_files.outputs.backend_any_changed }}
      renovate: ${{ steps.changed_files.outputs.renovate_any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed_files
        with:
          files_yaml: |
            frontend:
              - frontend/**
            backend:
              - backend/**
            renovate:
              - renovate.json
  frontend:
    runs-on: ubuntu-latest
    needs: changed_types
    if: needs.changed_types.outputs.frontend == 'true'
    steps:
      - run: echo "Frontend changed."
  backend:
    runs-on: ubuntu-latest
    needs: changed_types
    if: needs.changed_types.outputs.backend == 'true'
    steps:
      - run: echo "Backend changed."
  renovate:
    runs-on: ubuntu-latest
    needs: changed_types
    if: needs.changed_types.outputs.renovate == 'true'
    steps:
      - run: echo "Renovate config changed."
