name: CI Frontend
on:
  pull_request: 
    paths:
      - 'frontend/**'
  push:
    branches: [main] # デフォルトブランチでキャッシュを保持するために main ブランチでも実行
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Frontend changed."
