name: Reusable workflow example

on:
  pull_request:
    paths:
      - ".github/workflows/reusable-workflow-b.yaml"
  schedule:
    - cron: "*/10 * * * *"

jobs:
  call-workflow-1:
    uses: korosuke613/playground/.github/workflows/reusable-workflow-a.yaml@reuse-workflow-v1
    with:
      username: korosuke613
    secrets:
      token: "this is token"

