on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/setup-go.yaml'

jobs:
  using-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.16
          cache: true
          cache-dependency-path: go/helloworld/go.sum
      - run: go test ./... -v -cover
        working-directory: go/helloworld
