on: 
  push:
    paths:
      - ".github/workflows/setup-node.yaml"

jobs:
  using-cache:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: "javascript/mswjs"
    steps:
      - uses: actions/checkout@v2
      - run: cd javascript/mswjs
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm run test
