on:
  push:
    paths:
      - ".github/workflows/setup-node.yaml"
      - "javascript/mswjs/**"
      - "javascript/strykerjs"

jobs:
  using-cache-single:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "javascript/mswjs"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: 'javascript/mswjs'
      - run: npm ci
      - run: npm run test

  using-cache-multi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: |
            javascript/mswjs
            javascript/strykerjs
      - name: '[mswjs] npm ci'
        run: npm ci
        working-directory: "javascript/mswjs"
      - name: '[mswjs] npm run test'
        run: npm run test
        working-directory: "javascript/mswjs"
      - name: '[strykerjs] npm ci'
        run: npm ci
        working-directory: "javascript/strykerjs"
      - name: '[strykerjs] npm run test:mutation'
        run: npm run test:mutation
        working-directory: "javascript/strykerjs"
