on:
  workflow_dispatch:
    inputs:
      archive_id:
        type: string
        description: 'The ID of the archive to download'
        required: true
      dry-run:
        type: boolean
        description: 'Whether to run the workflow without making changes'
        default: true
      environment:
        type: environment
        description: 'The environment to deploy to'
        required: true


jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Echo inputs
        run: echo "${{ github.event.inputs }}"
