on:
  workflow_dispatch:
    inputs:
      archive_id:
        type: string
        required: true
      environment:
        type: environment
        required: true
        default: 'staging'
      dry-run:
        type: boolean
        default: true

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Echo inputs
        run: echo "${{ github.event.inputs }}"
